[package]
name = "diebahn"
description = "Find all your travel information" # keep in sync with metainfo
authors = ["Julian Schmidhuber <mobile@schmidhuberj.de>", "Markus Göllnitz <camelcasenick@bewares.it>"]
homepage = "https://mobile.schmidhuberj.de/railway"
repository = "https://gitlab.com/schmiddi-on-mobile/railway"
version = "2.9.3"
license = "GPL-3.0-or-later"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.10", package = "gtk4", features = ["v4_14"] }
gdk = { version = "0.10", package = "gdk4" }
libadwaita = { version = "0.8", features = ["v1_7"] }
gettext-rs = { version = "0.7.2", features = ["gettext-system"] }

once_cell = "1.21.3"
tokio = { version = "1.44.2", features = ["rt", "macros", "rt-multi-thread", "time"] }
chrono = "0.4.41"
# A newer version is available, but that requires backend updates.
chrono-tz = "0.8"

log = "0.4.27"
env_logger = "0.11.8"

rcore = { version = "0.2", package = "railway-core", features = ["reqwest-requester", "rt-multi-thread", "serde"] }
rapi = { version = "0.2", package = "railway-api", features = ["rt-multi-thread"] }

serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
