[package]
name = "diebahn"
description = "A frontend for 'Deutsche Bahn'."
authors = ["Julian Schmidhuber <schmidhuberj2@protonmail.com>"]
homepage = "https://gitlab.com/Schmiddiii/diebahn"
version = "1.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.4.6", package = "gtk4" }
gdk = { version = "0.4.6", package = "gdk4" }
libadwaita = "0.1.0"
gettext-rs = "0.7.0"

once_cell = "1.0"
tokio = { version = "1.17.0", features = ["rt", "macros", "rt-multi-thread", "time"] }
chrono = "0.4.19"

log = "0.4.14"
env_logger = "0.9.0"

hafas-rs = { git = "https://gitlab.com/Schmiddiii/hafas-rs", rev = "129ec0d76a62bc61444a6bdae257a60c1bfbd98a", default-features = false, features = [ "hyper-requester", "all-profiles" ] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
