[package]
name = "diebahn"
description = "Travel with all your train information in one place"
authors = ["Julian Schmidhuber <schmidhuberj2@protonmail.com>"]
homepage = "https://mobile.schmidhuberj.de/railway"
repository = "https://gitlab.com/schmiddi-on-mobile/railway"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.7.2", package = "gtk4", features = ["v4_12"] }
gdk = { version = "0.7.2", package = "gdk4" }
libadwaita = { version = "0.5.2", features = ["v1_4"] }
gettext-rs = { version = "0.7.0", features = ["gettext-system"] }

once_cell = "1.18.0"
tokio = { version = "1.32.0", features = ["rt", "macros", "rt-multi-thread", "time"] }
chrono = "0.4.28"

log = "0.4.20"
env_logger = "0.10.0"

hafas-rs = { version = "0.1.0", default-features = false, features = [ "hyper-requester", "all-profiles", "rt-multi-thread" ] }

serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
