
name: Create crate dist
on:
  push:
    tags:
      - '*'

jobs:
  crate-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create crate dist
        uses: projg2/crate-dist-action@v1
        with:
          directories: .

